// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('add navigation item', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('add navigation item', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(5) > .RuiSidebar-listItem-82 > .MuiListItemText-root > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".MuiButton-outlined > .MuiButton-label")).click()
    await driver.findElement(By.css(".Field__StyledField-qlv3w9-0:nth-child(1) > .TextInput__InputWrapper-sc-9jjo1u-0")).click()
    await driver.findElement(By.id("name_NavigationItemForm1")).click()
    await driver.findElement(By.id("name_NavigationItemForm1")).sendKeys("Mobile Accesories")
    await driver.findElement(By.id("url_NavigationItemForm1")).click()
    await driver.findElement(By.css(".Field__StyledField-qlv3w9-0:nth-child(3) .Checkbox__StyledLabel-sc-1abqzv2-2")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-root:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("url_NavigationItemForm1")).click()
    {
      const element = await driver.findElement(By.css(".irAaBa"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".irAaBa"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".irAaBa"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".irAaBa")).click()
    await driver.findElement(By.css(".MuiDialogContent-root")).click()
    await driver.findElement(By.id("url_NavigationItemForm1")).click()
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) > .MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("url_NavigationItemForm1")).sendKeys("Mobile Accesories")
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) > .MuiButton-label")).click()
  })
})
