// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('duplicate a product', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('duplicate a product', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(2) > .RuiSidebar-listItem-82 > .MuiListItemText-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-label > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-label > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiMenu-list")).click()
    await driver.findElement(By.css("#bulk-actions-menu > div:nth-child(1)")).click()
    await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label")).click()
    await driver.findElement(By.css(".MuiListItemText-secondary")).click()
    {
      const element = await driver.findElement(By.css(".MuiListItemText-secondary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiListItem-root:nth-child(2)")).click()
    await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label")).click()
    await driver.findElement(By.css(".MuiIconButton-root:nth-child(2)")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("a:nth-child(2) > .MuiListItem-dense > .MuiListItemText-root")).click()
    await driver.findElement(By.name("attributeLabel")).click()
    await driver.findElement(By.name("attributeLabel")).sendKeys("Sun Glasses")
    await driver.findElement(By.name("optionTitle")).click()
    await driver.findElement(By.name("optionTitle")).sendKeys("Ray ")
    await driver.findElement(By.name("attributeLabel")).click()
    await driver.findElement(By.name("attributeLabel")).sendKeys("Ray BAn")
    await driver.findElement(By.name("optionTitle")).click()
    await driver.findElement(By.name("optionTitle")).sendKeys("black")
    await driver.findElement(By.name("title")).click()
    await driver.findElement(By.name("title")).sendKeys("Sun Glasses")
    await driver.findElement(By.css(".css-tj5bde-Svg")).click()
    await driver.findElement(By.id("react-select-3-option-166")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) .form-control")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(1) .form-control")).sendKeys("10.0")
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .numeric-input .form-control")).click()
    await driver.findElement(By.css(".MuiGrid-root:nth-child(2) > .numeric-input .form-control")).sendKeys("15.0")
    await driver.findElement(By.name("width")).click()
    await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label")).click()
  })
})
