// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('quantity of product', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('quantity of product', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    {
      const element = await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(2) > .RuiSidebar-listItem-82 > .MuiListItemText-root > span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(2) > .RuiSidebar-listItem-82 > .MuiListItemText-root > span")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(1) > .MuiTableCell-root:nth-child(8) .MuiSvgIcon-root")).click()
    await driver.findElement(By.css("a .MuiIconButton-label > .MuiSvgIcon-root")).click()
    await driver.executeScript("window.scrollTo(0,1533)")
    await driver.findElement(By.css(".MuiFormControlLabel-root:nth-child(2) .PrivateSwitchBase-input-537")).click()
    await driver.findElement(By.name("inventoryInStock")).click()
    await driver.findElement(By.name("inventoryInStock")).sendKeys("10")
    await driver.findElement(By.name("lowInventoryWarningThreshold")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.name("lowInventoryWarningThreshold")).sendKeys("2")
    await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
